# Generated by Django 3.0.7 on 2020-06-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='state',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED'), ('archived', 'ARCHIVED')], default='draft', max_length=20),
        ),
    ]
