# Generated by Django 3.0.7 on 2020-06-21 23:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200621_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True),
        ),
    ]
